#!/usr/bin/env python3
# Deterministically bundle Note's modular Luau source into standalone main.lua.

from __future__ import annotations

import base64
from collections import defaultdict, deque
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "src"
OUTPUT = ROOT / "main.lua"

GENERATED_HEADER = '''--[[
    Note UI Library
    Generated from the modular source under /src.
    Do not edit this file directly.
]]

'''

MODULE_LOADER = '''local __modules = {}
local __cache = {}
local __loading = {}

local function __require(moduleId)
    if __cache[moduleId] ~= nil then
        return __cache[moduleId]
    end
    local loader = __modules[moduleId]
    if not loader then
        error(string.format("[Note] Bundled module not found: %s", tostring(moduleId)), 2)
    end
    if __loading[moduleId] then
        error(string.format("[Note] Circular bundled require: %s", tostring(moduleId)), 2)
    end
    __loading[moduleId] = true
    local ok, result = xpcall(function()
        return loader(__require)
    end, debug.traceback)
    __loading[moduleId] = nil
    if not ok then
        error(result, 0)
    end
    __cache[moduleId] = result
    return result
end

'''

RUNTIME_WRAPPER = r'''local __payload = [=[
__PAYLOAD__
]=]

local function __decodeBase64(encoded)
    local alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
    local lookup = {}
    for index = 1, #alphabet do
        lookup[string.byte(alphabet, index)] = index - 1
    end

    local output = {}
    local buffer = 0
    local bits = 0
    for index = 1, #encoded do
        local value = lookup[string.byte(encoded, index)]
        if value ~= nil then
            buffer = buffer * 64 + value
            bits += 6
            if bits >= 8 then
                bits -= 8
                output[#output + 1] = string.char(math.floor(buffer / (2 ^ bits)) % 256)
                buffer %= 2 ^ bits
            end
        end
    end
    return table.concat(output)
end

local function __decompressLzss(packed)
    local bytes = {}
    local cursor = 1
    while cursor <= #packed do
        local flags = string.byte(packed, cursor)
        cursor += 1
        for bit = 0, 7 do
            if cursor > #packed then
                break
            end
            local isMatch = math.floor(flags / (2 ^ bit)) % 2 == 1
            if isMatch then
                local high, low, encodedLength = string.byte(packed, cursor, cursor + 2)
                cursor += 3
                local offset = high * 256 + low
                local length = encodedLength + 3
                if offset <= 0 or offset > #bytes then
                    error("[Note] Invalid compressed distribution payload", 0)
                end
                for _ = 1, length do
                    bytes[#bytes + 1] = bytes[#bytes - offset + 1]
                end
            else
                bytes[#bytes + 1] = string.byte(packed, cursor)
                cursor += 1
            end
        end
    end

    local chunks = {}
    local chunkSize = 1024
    for index = 1, #bytes, chunkSize do
        chunks[#chunks + 1] = string.char(table.unpack(
            bytes,
            index,
            math.min(index + chunkSize - 1, #bytes)
        ))
    end
    return table.concat(chunks)
end

local source = __decompressLzss(__decodeBase64(__payload))
local compiler = loadstring
if type(compiler) ~= "function" then
    error("[Note] loadstring is required to execute the generated distribution", 0)
end
local chunk, compileError = compiler(source)
if not chunk then
    error("[Note] Generated distribution failed to compile: " .. tostring(compileError), 0)
end
return chunk()
'''


def module_id(path: Path) -> str:
    return path.relative_to(ROOT).with_suffix("").as_posix()


def indent(source: str, spaces: int = 4) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line if line else "" for line in source.splitlines())


def build_source() -> str:
    files = sorted(SOURCE_ROOT.rglob("*.lua"), key=lambda path: path.as_posix())
    if not files:
        raise SystemExit("No source modules found")

    chunks = [MODULE_LOADER]
    for path in files:
        source = path.read_text(encoding="utf-8").replace("\r\n", "\n").rstrip()
        module = module_id(path)
        chunks.append(f'__modules["{module}"] = function(require)\n')
        chunks.append(indent(source))
        chunks.append("\nend\n\n")
    chunks.append('return __require("src/init")\n')

    # Removing indentation and empty lines before compression is syntax-preserving,
    # because module source contains no line comments or long-bracket string bodies.
    readable = "".join(chunks)
    return "\n".join(line.strip() for line in readable.splitlines() if line.strip()) + "\n"


def compress_lzss(data: bytes, window: int = 65535, max_length: int = 258, candidate_limit: int = 128) -> bytes:
    positions: dict[bytes, deque[int]] = defaultdict(deque)
    tokens: list[int | tuple[int, int]] = []
    cursor = 0

    while cursor < len(data):
        best_length = 0
        best_offset = 0
        if cursor + 2 < len(data):
            key = data[cursor:cursor + 3]
            candidates = positions[key]
            while candidates and cursor - candidates[0] > window:
                candidates.popleft()

            checked = 0
            for previous in reversed(candidates):
                offset = cursor - previous
                if offset <= 0 or offset > window:
                    continue
                length = 3
                limit = min(max_length, len(data) - cursor)
                while length < limit and data[previous + length] == data[cursor + length]:
                    length += 1
                if length > best_length:
                    best_length = length
                    best_offset = offset
                    if length == limit:
                        break
                checked += 1
                if checked >= candidate_limit:
                    break

        if best_length >= 3:
            tokens.append((best_offset, best_length))
            end = cursor + best_length
            while cursor < end:
                if cursor + 2 < len(data):
                    positions[data[cursor:cursor + 3]].append(cursor)
                cursor += 1
        else:
            tokens.append(data[cursor])
            if cursor + 2 < len(data):
                positions[data[cursor:cursor + 3]].append(cursor)
            cursor += 1

    packed = bytearray()
    token_index = 0
    while token_index < len(tokens):
        flag_index = len(packed)
        packed.append(0)
        flags = 0
        for bit in range(8):
            if token_index >= len(tokens):
                break
            token = tokens[token_index]
            token_index += 1
            if isinstance(token, tuple):
                flags |= 1 << bit
                offset, length = token
                packed.extend(((offset >> 8) & 255, offset & 255, length - 3))
            else:
                packed.append(token)
        packed[flag_index] = flags
    return bytes(packed)


def decompress_lzss_for_check(packed: bytes) -> bytes:
    output = bytearray()
    cursor = 0
    while cursor < len(packed):
        flags = packed[cursor]
        cursor += 1
        for bit in range(8):
            if cursor >= len(packed):
                break
            if flags & (1 << bit):
                if cursor + 2 >= len(packed):
                    raise ValueError("truncated match token")
                offset = packed[cursor] * 256 + packed[cursor + 1]
                length = packed[cursor + 2] + 3
                cursor += 3
                if offset <= 0 or offset > len(output):
                    raise ValueError("invalid match offset")
                for _ in range(length):
                    output.append(output[-offset])
            else:
                output.append(packed[cursor])
                cursor += 1
    return bytes(output)


def build() -> str:
    source = build_source().encode("utf-8")
    packed = compress_lzss(source)
    if decompress_lzss_for_check(packed) != source:
        raise RuntimeError("internal LZSS verification failed")
    encoded = base64.b64encode(packed).decode("ascii")
    payload = "\n".join(encoded[index:index + 100] for index in range(0, len(encoded), 100))
    return GENERATED_HEADER + RUNTIME_WRAPPER.replace("__PAYLOAD__", payload)


def main() -> None:
    output = build()
    OUTPUT.write_text(output, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(output):,} bytes)")


if __name__ == "__main__":
    main()
